import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "en" | "ru" | "kz";

const STORAGE_KEY = "app.lang";

const dict = {
  en: {
    "nav.home": "Home",
    "nav.browse": "Browse Requests",
    "nav.myRequests": "My Requests",
    "nav.admin": "Admin",
    "nav.map": "Map",
    "nav.login": "Log In",
    "nav.signup": "Sign Up",
    "nav.signout": "Sign Out",
    "role.user": "Customer",
    "role.worker": "Worker",
    "role.company": "Company",
    "role.admin": "Admin",

    "hero.title1": "Find Repair Pros.",
    "hero.title2": "Your Price.",
    "hero.subtitle": "Post your repair or maintenance request, get competitive offers from verified workers, and negotiate the best price — all in one platform.",
    "hero.browse": "Browse Requests",
    "hero.joinWorker": "Join as Worker",

    "cats.title": "Popular Categories",
    "cats.subtitle": "Find the right specialist for any job",
    "cats.jobs": "jobs",

    "recent.title": "Recent Requests",
    "recent.subtitle": "Latest service requests from our community",
    "recent.viewAll": "View All",

    "how.title": "How It Works",
    "how.subtitle": "Simple 4-step process to get your job done",
    "how.s1t": "Post a Request",
    "how.s1d": "Describe the work, set a budget, and upload photos.",
    "how.s2t": "Get Offers",
    "how.s2d": "Verified workers send their price proposals.",
    "how.s3t": "Negotiate & Choose",
    "how.s3d": "Compare offers, chat with workers, pick the best fit.",
    "how.s4t": "Job Done & Rate",
    "how.s4d": "Work gets completed. Pay and leave a review.",

    "trust.t1": "Verified Workers",
    "trust.d1": "Every worker goes through identity and skill verification.",
    "trust.t2": "Secure Chat",
    "trust.d2": "Communicate safely through our built-in messaging system.",
    "trust.t3": "Honest Reviews",
    "trust.d3": "Transparent rating system based on real completed jobs.",

    "cta.title": "Ready to Get Started?",
    "cta.subtitle": "Join thousands of customers and workers already using FixFlow.",
    "cta.create": "Create Account",

    "ai.title": "For You",
    "ai.subtitle": "AI-picked services based on your season and interests",
    "ai.placeholder": 'Describe your task, e.g. "leaking faucet"',
    "ai.recommend": "Recommend",

    "footer.tagline": "Connecting customers with trusted repair professionals. Fast, reliable, transparent.",
    "footer.platform": "Platform",
    "footer.browse": "Browse Requests",
    "footer.how": "How It Works",
    "footer.becomeWorker": "Become a Worker",
    "footer.support": "Support",
    "footer.help": "Help Center",
    "footer.safety": "Safety",
    "footer.contact": "Contact Us",
    "footer.legal": "Legal",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.rights": "All rights reserved.",

    "card.offer": "offer",
    "card.offers": "offers",

    "req.title": "Service Requests",
    "req.activeCount": "active requests",
    "req.post": "Post a Request",
    "req.workerHint": "Browse & submit offers below",
    "req.adminHint": "Moderation mode active",
    "req.searchPlaceholder": "Search requests...",
    "req.filters": "Filters",
    "req.clearAll": "Clear all",
    "req.category": "Category",
    "req.allCategories": "All categories",
    "req.city": "City",
    "req.allCities": "All cities",
    "req.minRating": "Minimum Poster Rating",
    "req.applyFilters": "Apply Filters",
    "req.noFound": "No requests found",
    "req.noFoundHint": "Try adjusting your search or filters",
    "req.selectCity": "Select your city",
    "req.selectCityHint": "Choose a city to see nearby requests first",
    "req.skipCity": "Skip — show all requests",
    "req.selectCityShort": "Select city",

    "rd.back": "Back to Requests",
    "rd.notFound": "Request not found",
    "rd.desiredPeriod": "Desired period:",
    "rd.address": "Address:",
    "rd.submitOffer": "Submit Your Offer",
    "rd.proposedPrice": "Your Proposed Price (₸)",
    "rd.message": "Message to Customer",
    "rd.messagePlaceholder": "Describe your experience and availability...",
    "rd.submit": "Submit Offer",
    "rd.cancel": "Cancel",
    "rd.offers": "Offers",
    "rd.rateCustomer": "Rate customer:",
    "rd.rateWorker": "Rate worker:",
    "rd.save": "Save",
    "rd.rated": "✓ Rated",
    "rd.accept": "Accept",
    "rd.accepted": "Accepted",
    "rd.workCompletion": "Work Completion",
    "rd.completionHint": "Both the customer and worker must confirm the work is complete to archive this request.",
    "rd.customer": "Customer",
    "rd.worker": "Worker",
    "rd.confirmed": "Confirmed",
    "rd.pending": "Pending",
    "rd.markComplete": "Mark Complete",
    "rd.budget": "Budget",
    "rd.negotiable": "Negotiable",
    "rd.initialPrice": "Initial customer price",
    "rd.postedBy": "Posted By",
    "rd.you": "You",
    "rd.contactAfter": "Contact after assignment",
    "rd.makeOffer": "Make an Offer",
    "rd.offerSubmitted": "Offer Submitted",
    "rd.youConfirmed": "You Confirmed Complete",
    "rd.markWorkComplete": "Mark Work Complete",
    "rd.loginOffer": "Log in to Make an Offer",

    "sc.greeting": "👋 Hi! I'm the FixFlow assistant. Ask me anything about how the platform works — creating requests, offers, ratings, and more.",
    "sc.title": "FixFlow Assistant",
    "sc.subtitle": "Ask me anything",
    "sc.suggested": "Suggested:",
    "sc.placeholder": "Type your question...",
    "sc.s1": "How do I create a request?",
    "sc.s2": "How do offers work?",
    "sc.s3": "How do I mark a job as done?",
    "sc.s4": "How does the rating system work?",

    "auth.welcomeBack": "Welcome Back",
    "auth.signInSubtitle": "Sign in to your FixFlow account",
    "auth.email": "Email",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.noAccount": "Don't have an account?",
    "auth.fillFields": "Please fill in all fields",
    "auth.welcomeBackToast": "Welcome back!",

    "reg.title": "Create Account",
    "reg.subtitle": "Join FixFlow today",
    "reg.fullName": "Full Name *",
    "reg.fullNamePlaceholder": "John Doe",
    "reg.emailReq": "Email *",
    "reg.phone": "Phone Number",
    "reg.phonePlaceholder": "+7 (___) ___-__-__",
    "reg.passwordReq": "Password *",
    "reg.create": "Create Account",
    "reg.haveAccount": "Already have an account?",
    "reg.fillRequired": "Please fill in all required fields",
    "reg.companyNameRequired": "Please enter your company name",
    "reg.createdToast": "Account created successfully!",
    "reg.alreadyExisted": "Account already existed, so you were signed in.",
    "reg.roleCustomer": "I need repairs",
    "reg.roleWorker": "I provide services",
    "reg.roleCompany": "We provide services",
    "reg.companyDetails": "Company Details",
    "reg.companyName": "Company Name *",
    "reg.companyNamePlaceholder": "Acme Corp",
    "reg.companyDesc": "Description",
    "reg.companyDescPlaceholder": "What does your company do?",
    "reg.companyAddress": "Address",
    "reg.companyAddressPlaceholder": "123 Main St",
    "reg.taxId": "Tax ID / INN",
    "reg.website": "Website",

    "prof.user": "User",
    "prof.yourRating": "Your Rating",
    "prof.basedOnReviews": "Based on customer reviews",
    "prof.review": "review",
    "prof.reviews": "reviews",
    "prof.noReviews": "No reviews yet. Complete jobs to start earning ratings.",
    "prof.personalInfo": "Personal Information",
    "prof.personalInfoDesc": "Update your personal details",
    "prof.email": "Email",
    "prof.displayName": "Display Name",
    "prof.displayNamePlaceholder": "Your name",
    "prof.phone": "Phone",
    "prof.faceVerification": "Face Verification",
    "prof.faceVerificationDesc": "Verify your identity with a quick face scan. Required to build customer trust.",
    "prof.faceVerified": "Face verified",
    "prof.scanFace": "Scan Face",
    "prof.rescan": "Re-scan",
    "prof.certificate": "Qualification Certificate",
    "prof.certificateDesc": "Upload a PDF proving you are a qualified professional. Visible to customers reviewing your offers.",
    "prof.certUploaded": "Certificate uploaded",
    "prof.view": "View",
    "prof.noCert": "No certificate uploaded yet.",
    "prof.replaceCert": "Replace Certificate",
    "prof.uploadCert": "Upload PDF Certificate",
    "prof.pdfHint": "PDF only, max 10MB.",
    "prof.companyInfo": "Company Information",
    "prof.companyInfoDesc": "Manage your company details",
    "prof.companyName": "Company Name",
    "prof.description": "Description",
    "prof.descriptionPlaceholder": "Describe your company...",
    "prof.address": "Address",
    "prof.taxId": "Tax ID / BIN",
    "prof.website": "Website",
    "prof.save": "Save Changes",
    "prof.invalidFile": "Invalid file",
    "prof.invalidFileDesc": "Only PDF files are allowed.",
    "prof.fileTooLarge": "File too large",
    "prof.fileTooLargeDesc": "Max size is 10MB.",
    "prof.certUploadedToast": "Certificate uploaded",
    "prof.certUploadedDesc": "Your qualification certificate is now visible.",
    "prof.uploadFailed": "Upload failed",
    "prof.certRemoved": "Certificate removed",
    "prof.error": "Error",
    "prof.profileUpdated": "Profile updated",
    "prof.profileUpdatedDesc": "Your changes have been saved.",

    "new.back": "Back to Requests",
    "new.title": "Post a New Request",
    "new.subtitle": "Describe the work you need done and get offers from professionals",
    "new.titleLabel": "Title *",
    "new.titlePlaceholder": "e.g. Fix leaking kitchen faucet",
    "new.category": "Category *",
    "new.selectCategory": "Select a category",
    "new.description": "Description *",
    "new.descriptionPlaceholder": "Describe the problem in detail...",
    "new.photos": "Photos (up to 5)",
    "new.maxPhotos": "Max 5 photos",
    "new.city": "City",
    "new.cityPlaceholder": "e.g. Almaty",
    "new.district": "District",
    "new.districtPlaceholder": "e.g. Bostandyk",
    "new.address": "Address",
    "new.addressPlaceholder": "Street, building, apartment",
    "new.budget": "Budget (₸)",
    "new.budgetPlaceholder": "Your expected price",
    "new.aiSuggest": "AI Suggest",
    "new.aiEstimate": "AI estimate (₸)",
    "new.useAmount": "Use",
    "new.timeRange": "Desired Time Range",
    "new.timeRangeHint": "When should the work be done?",
    "new.startDate": "Start date",
    "new.endDate": "End date",
    "new.posting": "Posting...",
    "new.post": "Post Request",
    "new.fillRequired": "Please fill in title, description, and category",
    "new.posted": "Request posted!",
    "new.aiError": "AI error",
    "new.titleCatFirst": "Enter title and category first",
    "new.error": "Error",

    "my.title": "My Requests",
    "my.active": "Active",
    "my.archive": "Archive",
    "my.noActiveJobs": "No active jobs yet",
    "my.noActive": "No active requests",
    "my.browseRequests": "Browse Requests",
    "my.postRequest": "Post a Request",
    "my.noArchived": "No archived requests",
    "my.archivedHint": "Completed and cancelled requests will appear here",
    "my.myJob": "My Job",

    "adm.accessOnly": "Admin access only",
    "adm.title": "Admin Panel",
    "adm.subtitle": "Manage requests and users",
    "adm.requests": "Requests",
    "adm.users": "Users",
    "adm.noCity": "No city",
    "adm.budget": "Budget",
    "adm.noPhone": "No phone",
    "adm.noName": "(no name)",
    "adm.noRequests": "No requests",
    "adm.noUsers": "No users",
    "adm.editRequest": "Edit Request",
    "adm.editUser": "Edit User",
    "adm.fTitle": "Title",
    "adm.fDescription": "Description",
    "adm.fCategory": "Category",
    "adm.fStatus": "Status",
    "adm.fBudget": "Budget",
    "adm.fCity": "City",
    "adm.fDisplayName": "Display name",
    "adm.fPhone": "Phone",
    "adm.fRole": "Role",
    "adm.selectRole": "Select role",
    "adm.cancel": "Cancel",
    "adm.save": "Save",
    "adm.confirmDelete": "Delete this request permanently?",
    "adm.requestDeleted": "Request deleted",
    "adm.requestUpdated": "Request updated",
    "adm.userUpdated": "User updated",
  },
  ru: {
    "nav.home": "Главная",
    "nav.browse": "Заявки",
    "nav.myRequests": "Мои заявки",
    "nav.admin": "Админ",
    "nav.map": "Карта",
    "nav.login": "Войти",
    "nav.signup": "Регистрация",
    "nav.signout": "Выйти",
    "role.user": "Клиент",
    "role.worker": "Мастер",
    "role.company": "Компания",
    "role.admin": "Админ",

    "hero.title1": "Найди мастера.",
    "hero.title2": "Твоя цена.",
    "hero.subtitle": "Размещайте заявки на ремонт, получайте предложения от проверенных мастеров и договаривайтесь о лучшей цене — всё в одной платформе.",
    "hero.browse": "Смотреть заявки",
    "hero.joinWorker": "Стать мастером",

    "cats.title": "Популярные категории",
    "cats.subtitle": "Найдите специалиста под любую задачу",
    "cats.jobs": "заявок",

    "recent.title": "Свежие заявки",
    "recent.subtitle": "Последние заявки от нашего сообщества",
    "recent.viewAll": "Смотреть все",

    "how.title": "Как это работает",
    "how.subtitle": "Простой процесс из 4 шагов",
    "how.s1t": "Создайте заявку",
    "how.s1d": "Опишите работу, укажите бюджет и загрузите фото.",
    "how.s2t": "Получите предложения",
    "how.s2d": "Проверенные мастера присылают свои цены.",
    "how.s3t": "Договоритесь и выберите",
    "how.s3d": "Сравните предложения, общайтесь и выбирайте лучшее.",
    "how.s4t": "Работа сделана — оцените",
    "how.s4d": "Работа выполнена. Оплатите и оставьте отзыв.",

    "trust.t1": "Проверенные мастера",
    "trust.d1": "Каждый мастер проходит проверку личности и навыков.",
    "trust.t2": "Безопасный чат",
    "trust.d2": "Общайтесь безопасно через встроенную систему сообщений.",
    "trust.t3": "Честные отзывы",
    "trust.d3": "Прозрачные рейтинги на основе реальных работ.",

    "cta.title": "Готовы начать?",
    "cta.subtitle": "Тысячи клиентов и мастеров уже пользуются FixFlow.",
    "cta.create": "Создать аккаунт",

    "ai.title": "Для вас",
    "ai.subtitle": "Услуги, подобранные ИИ под ваш сезон и интересы",
    "ai.placeholder": 'Опишите задачу, например «течет кран»',
    "ai.recommend": "Подобрать",

    "footer.tagline": "Соединяем клиентов с надежными мастерами. Быстро, надежно, прозрачно.",
    "footer.platform": "Платформа",
    "footer.browse": "Заявки",
    "footer.how": "Как это работает",
    "footer.becomeWorker": "Стать мастером",
    "footer.support": "Поддержка",
    "footer.help": "Центр помощи",
    "footer.safety": "Безопасность",
    "footer.contact": "Связаться с нами",
    "footer.legal": "Правовая информация",
    "footer.terms": "Условия использования",
    "footer.privacy": "Политика конфиденциальности",
    "footer.rights": "Все права защищены.",

    "card.offer": "предложение",
    "card.offers": "предложений",

    "req.title": "Заявки на услуги",
    "req.activeCount": "активных заявок",
    "req.post": "Создать заявку",
    "req.workerHint": "Смотрите и оставляйте предложения ниже",
    "req.adminHint": "Режим модерации активен",
    "req.searchPlaceholder": "Поиск заявок...",
    "req.filters": "Фильтры",
    "req.clearAll": "Очистить",
    "req.category": "Категория",
    "req.allCategories": "Все категории",
    "req.city": "Город",
    "req.allCities": "Все города",
    "req.minRating": "Мин. рейтинг автора",
    "req.applyFilters": "Применить",
    "req.noFound": "Заявки не найдены",
    "req.noFoundHint": "Попробуйте изменить поиск или фильтры",
    "req.selectCity": "Выберите город",
    "req.selectCityHint": "Выберите город, чтобы видеть заявки рядом",
    "req.skipCity": "Пропустить — показать все",
    "req.selectCityShort": "Выбрать город",

    "rd.back": "К заявкам",
    "rd.notFound": "Заявка не найдена",
    "rd.desiredPeriod": "Желаемый период:",
    "rd.address": "Адрес:",
    "rd.submitOffer": "Отправить предложение",
    "rd.proposedPrice": "Ваша цена (₸)",
    "rd.message": "Сообщение клиенту",
    "rd.messagePlaceholder": "Опишите ваш опыт и доступность...",
    "rd.submit": "Отправить",
    "rd.cancel": "Отмена",
    "rd.offers": "Предложения",
    "rd.rateCustomer": "Оценить клиента:",
    "rd.rateWorker": "Оценить мастера:",
    "rd.save": "Сохранить",
    "rd.rated": "✓ Оценено",
    "rd.accept": "Принять",
    "rd.accepted": "Принято",
    "rd.workCompletion": "Завершение работы",
    "rd.completionHint": "И клиент, и мастер должны подтвердить завершение, чтобы заявка была закрыта.",
    "rd.customer": "Клиент",
    "rd.worker": "Мастер",
    "rd.confirmed": "Подтверждено",
    "rd.pending": "Ожидание",
    "rd.markComplete": "Подтвердить",
    "rd.budget": "Бюджет",
    "rd.negotiable": "Договорная",
    "rd.initialPrice": "Начальная цена клиента",
    "rd.postedBy": "Автор",
    "rd.you": "Вы",
    "rd.contactAfter": "Связь после назначения",
    "rd.makeOffer": "Сделать предложение",
    "rd.offerSubmitted": "Предложение отправлено",
    "rd.youConfirmed": "Вы подтвердили завершение",
    "rd.markWorkComplete": "Завершить работу",
    "rd.loginOffer": "Войдите, чтобы предложить",

    "sc.greeting": "👋 Привет! Я ассистент FixFlow. Спросите меня о работе платформы — заявки, предложения, рейтинги и многое другое.",
    "sc.title": "Ассистент FixFlow",
    "sc.subtitle": "Спросите что угодно",
    "sc.suggested": "Подсказки:",
    "sc.placeholder": "Введите вопрос...",
    "sc.s1": "Как создать заявку?",
    "sc.s2": "Как работают предложения?",
    "sc.s3": "Как отметить работу выполненной?",
    "sc.s4": "Как работает рейтинговая система?",

    "auth.welcomeBack": "С возвращением",
    "auth.signInSubtitle": "Войдите в свой аккаунт FixFlow",
    "auth.email": "Email",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Пароль",
    "auth.signIn": "Войти",
    "auth.noAccount": "Нет аккаунта?",
    "auth.fillFields": "Заполните все поля",
    "auth.welcomeBackToast": "С возвращением!",

    "reg.title": "Создать аккаунт",
    "reg.subtitle": "Присоединяйтесь к FixFlow",
    "reg.fullName": "Полное имя *",
    "reg.fullNamePlaceholder": "Иван Иванов",
    "reg.emailReq": "Email *",
    "reg.phone": "Номер телефона",
    "reg.phonePlaceholder": "+7 (___) ___-__-__",
    "reg.passwordReq": "Пароль *",
    "reg.create": "Создать аккаунт",
    "reg.haveAccount": "Уже есть аккаунт?",
    "reg.fillRequired": "Заполните все обязательные поля",
    "reg.companyNameRequired": "Укажите название компании",
    "reg.createdToast": "Аккаунт успешно создан!",
    "reg.alreadyExisted": "Аккаунт уже существовал, вы вошли в систему.",
    "reg.roleCustomer": "Мне нужен ремонт",
    "reg.roleWorker": "Я оказываю услуги",
    "reg.roleCompany": "Мы оказываем услуги",
    "reg.companyDetails": "Данные компании",
    "reg.companyName": "Название компании *",
    "reg.companyNamePlaceholder": "ООО Ромашка",
    "reg.companyDesc": "Описание",
    "reg.companyDescPlaceholder": "Чем занимается ваша компания?",
    "reg.companyAddress": "Адрес",
    "reg.companyAddressPlaceholder": "ул. Главная, 123",
    "reg.taxId": "ИНН / БИН",
    "reg.website": "Веб-сайт",

    "prof.user": "Пользователь",
    "prof.yourRating": "Ваш рейтинг",
    "prof.basedOnReviews": "На основе отзывов клиентов",
    "prof.review": "отзыв",
    "prof.reviews": "отзывов",
    "prof.noReviews": "Пока нет отзывов. Выполняйте заказы, чтобы получать оценки.",
    "prof.personalInfo": "Личная информация",
    "prof.personalInfoDesc": "Обновите свои личные данные",
    "prof.email": "Email",
    "prof.displayName": "Отображаемое имя",
    "prof.displayNamePlaceholder": "Ваше имя",
    "prof.phone": "Телефон",
    "prof.faceVerification": "Верификация лица",
    "prof.faceVerificationDesc": "Подтвердите личность с помощью быстрого сканирования лица. Повышает доверие клиентов.",
    "prof.faceVerified": "Лицо подтверждено",
    "prof.scanFace": "Сканировать лицо",
    "prof.rescan": "Пересканировать",
    "prof.certificate": "Сертификат квалификации",
    "prof.certificateDesc": "Загрузите PDF, подтверждающий вашу квалификацию. Виден клиентам при рассмотрении предложений.",
    "prof.certUploaded": "Сертификат загружен",
    "prof.view": "Открыть",
    "prof.noCert": "Сертификат еще не загружен.",
    "prof.replaceCert": "Заменить сертификат",
    "prof.uploadCert": "Загрузить PDF сертификат",
    "prof.pdfHint": "Только PDF, до 10МБ.",
    "prof.companyInfo": "Информация о компании",
    "prof.companyInfoDesc": "Управляйте данными вашей компании",
    "prof.companyName": "Название компании",
    "prof.description": "Описание",
    "prof.descriptionPlaceholder": "Опишите вашу компанию...",
    "prof.address": "Адрес",
    "prof.taxId": "ИНН / БИН",
    "prof.website": "Веб-сайт",
    "prof.save": "Сохранить изменения",
    "prof.invalidFile": "Неверный файл",
    "prof.invalidFileDesc": "Разрешены только PDF файлы.",
    "prof.fileTooLarge": "Файл слишком большой",
    "prof.fileTooLargeDesc": "Максимальный размер 10МБ.",
    "prof.certUploadedToast": "Сертификат загружен",
    "prof.certUploadedDesc": "Ваш сертификат теперь виден.",
    "prof.uploadFailed": "Ошибка загрузки",
    "prof.certRemoved": "Сертификат удален",
    "prof.error": "Ошибка",
    "prof.profileUpdated": "Профиль обновлен",
    "prof.profileUpdatedDesc": "Ваши изменения сохранены.",

    "new.back": "К заявкам",
    "new.title": "Создать заявку",
    "new.subtitle": "Опишите работу и получите предложения от профессионалов",
    "new.titleLabel": "Заголовок *",
    "new.titlePlaceholder": "Например: починить кран на кухне",
    "new.category": "Категория *",
    "new.selectCategory": "Выберите категорию",
    "new.description": "Описание *",
    "new.descriptionPlaceholder": "Опишите проблему подробно...",
    "new.photos": "Фото (до 5)",
    "new.maxPhotos": "Максимум 5 фото",
    "new.city": "Город",
    "new.cityPlaceholder": "Например: Алматы",
    "new.district": "Район",
    "new.districtPlaceholder": "Например: Бостандык",
    "new.address": "Адрес",
    "new.addressPlaceholder": "Улица, дом, квартира",
    "new.budget": "Бюджет (₸)",
    "new.budgetPlaceholder": "Ваша ожидаемая цена",
    "new.aiSuggest": "ИИ подскажет",
    "new.aiEstimate": "Оценка ИИ (₸)",
    "new.useAmount": "Использовать",
    "new.timeRange": "Желаемое время",
    "new.timeRangeHint": "Когда должна быть выполнена работа?",
    "new.startDate": "Начало",
    "new.endDate": "Конец",
    "new.posting": "Публикация...",
    "new.post": "Опубликовать",
    "new.fillRequired": "Заполните заголовок, описание и категорию",
    "new.posted": "Заявка опубликована!",
    "new.aiError": "Ошибка ИИ",
    "new.titleCatFirst": "Сначала введите заголовок и категорию",
    "new.error": "Ошибка",

    "my.title": "Мои заявки",
    "my.active": "Активные",
    "my.archive": "Архив",
    "my.noActiveJobs": "Активных работ пока нет",
    "my.noActive": "Активных заявок нет",
    "my.browseRequests": "Смотреть заявки",
    "my.postRequest": "Создать заявку",
    "my.noArchived": "Нет архивных заявок",
    "my.archivedHint": "Завершенные и отмененные заявки появятся здесь",
    "my.myJob": "Моя работа",

    "adm.accessOnly": "Доступ только для админов",
    "adm.title": "Админ-панель",
    "adm.subtitle": "Управление заявками и пользователями",
    "adm.requests": "Заявки",
    "adm.users": "Пользователи",
    "adm.noCity": "Нет города",
    "adm.budget": "Бюджет",
    "adm.noPhone": "Нет телефона",
    "adm.noName": "(без имени)",
    "adm.noRequests": "Заявок нет",
    "adm.noUsers": "Пользователей нет",
    "adm.editRequest": "Редактировать заявку",
    "adm.editUser": "Редактировать пользователя",
    "adm.fTitle": "Заголовок",
    "adm.fDescription": "Описание",
    "adm.fCategory": "Категория",
    "adm.fStatus": "Статус",
    "adm.fBudget": "Бюджет",
    "adm.fCity": "Город",
    "adm.fDisplayName": "Отображаемое имя",
    "adm.fPhone": "Телефон",
    "adm.fRole": "Роль",
    "adm.selectRole": "Выберите роль",
    "adm.cancel": "Отмена",
    "adm.save": "Сохранить",
    "adm.confirmDelete": "Удалить эту заявку навсегда?",
    "adm.requestDeleted": "Заявка удалена",
    "adm.requestUpdated": "Заявка обновлена",
    "adm.userUpdated": "Пользователь обновлен",
  },
  kz: {
    "nav.home": "Басты бет",
    "nav.browse": "Өтінімдер",
    "nav.myRequests": "Менің өтінімдерім",
    "nav.admin": "Әкімші",
    "nav.map": "Карта",
    "nav.login": "Кіру",
    "nav.signup": "Тіркелу",
    "nav.signout": "Шығу",
    "role.user": "Тапсырыс беруші",
    "role.worker": "Шебер",
    "role.company": "Компания",
    "role.admin": "Әкімші",

    "hero.title1": "Шеберді тап.",
    "hero.title2": "Сенің бағаң.",
    "hero.subtitle": "Жөндеу өтінімін жариялаңыз, тексерілген шеберлерден ұсыныс алыңыз және ең тиімді бағаны келісіңіз — барлығы бір платформада.",
    "hero.browse": "Өтінімдерді қарау",
    "hero.joinWorker": "Шебер болу",

    "cats.title": "Танымал санаттар",
    "cats.subtitle": "Кез келген жұмысқа маман табыңыз",
    "cats.jobs": "өтінім",

    "recent.title": "Соңғы өтінімдер",
    "recent.subtitle": "Қауымдастықтың соңғы өтінімдері",
    "recent.viewAll": "Барлығын көру",

    "how.title": "Қалай жұмыс істейді",
    "how.subtitle": "4 қадамнан тұратын қарапайым процесс",
    "how.s1t": "Өтінім жасаңыз",
    "how.s1d": "Жұмысты сипаттаңыз, бюджет қойыңыз, сурет жүктеңіз.",
    "how.s2t": "Ұсыныстар алыңыз",
    "how.s2d": "Тексерілген шеберлер бағасын жібереді.",
    "how.s3t": "Келісіп таңдаңыз",
    "how.s3d": "Ұсыныстарды салыстырып, ең жақсысын таңдаңыз.",
    "how.s4t": "Орындалды — баға беріңіз",
    "how.s4d": "Жұмыс аяқталды. Төлеп, пікір қалдырыңыз.",

    "trust.t1": "Тексерілген шеберлер",
    "trust.d1": "Әр шебер тұлғасын және дағдыларын тексеруден өтеді.",
    "trust.t2": "Қауіпсіз чат",
    "trust.d2": "Кірістірілген хабарлама жүйесі арқылы қауіпсіз сөйлесіңіз.",
    "trust.t3": "Адал пікірлер",
    "trust.d3": "Нақты жұмыстарға негізделген ашық рейтинг жүйесі.",

    "cta.title": "Бастауға дайынсыз ба?",
    "cta.subtitle": "Мыңдаған клиенттер мен шеберлер FixFlow қолданады.",
    "cta.create": "Аккаунт құру",

    "ai.title": "Сізге арналған",
    "ai.subtitle": "Маусым мен қызығушылық бойынша ИИ ұсыныстары",
    "ai.placeholder": 'Тапсырманы сипаттаңыз, мысалы «кран ағады»',
    "ai.recommend": "Ұсыну",

    "footer.tagline": "Клиенттерді сенімді шеберлермен байланыстырамыз. Жылдам, сенімді, ашық.",
    "footer.platform": "Платформа",
    "footer.browse": "Өтінімдер",
    "footer.how": "Қалай жұмыс істейді",
    "footer.becomeWorker": "Шебер болу",
    "footer.support": "Қолдау",
    "footer.help": "Көмек орталығы",
    "footer.safety": "Қауіпсіздік",
    "footer.contact": "Бізбен байланыс",
    "footer.legal": "Заңды ақпарат",
    "footer.terms": "Қызмет шарттары",
    "footer.privacy": "Құпиялық саясаты",
    "footer.rights": "Барлық құқықтар қорғалған.",

    "card.offer": "ұсыныс",
    "card.offers": "ұсыныс",

    "req.title": "Қызмет өтінімдері",
    "req.activeCount": "белсенді өтінім",
    "req.post": "Өтінім жасау",
    "req.workerHint": "Төменде ұсыныстарды қараңыз",
    "req.adminHint": "Модерация режимі қосулы",
    "req.searchPlaceholder": "Өтінімдерді іздеу...",
    "req.filters": "Сүзгілер",
    "req.clearAll": "Тазалау",
    "req.category": "Санат",
    "req.allCategories": "Барлық санаттар",
    "req.city": "Қала",
    "req.allCities": "Барлық қалалар",
    "req.minRating": "Авторының мин. рейтингі",
    "req.applyFilters": "Қолдану",
    "req.noFound": "Өтінімдер табылмады",
    "req.noFoundHint": "Іздеуді немесе сүзгілерді өзгертіп көріңіз",
    "req.selectCity": "Қалаңызды таңдаңыз",
    "req.selectCityHint": "Жақын маңдағы өтінімдерді көру үшін қала таңдаңыз",
    "req.skipCity": "Өткізіп жіберу — барлығын көрсету",
    "req.selectCityShort": "Қала таңдау",

    "rd.back": "Өтінімдерге оралу",
    "rd.notFound": "Өтінім табылмады",
    "rd.desiredPeriod": "Қалаулы кезең:",
    "rd.address": "Мекенжай:",
    "rd.submitOffer": "Ұсынысыңызды жіберу",
    "rd.proposedPrice": "Сіздің бағаңыз (₸)",
    "rd.message": "Клиентке хабарлама",
    "rd.messagePlaceholder": "Тәжірибеңіз бен қол жетімділігіңізді сипаттаңыз...",
    "rd.submit": "Жіберу",
    "rd.cancel": "Бас тарту",
    "rd.offers": "Ұсыныстар",
    "rd.rateCustomer": "Клиентті бағалау:",
    "rd.rateWorker": "Шеберді бағалау:",
    "rd.save": "Сақтау",
    "rd.rated": "✓ Бағаланды",
    "rd.accept": "Қабылдау",
    "rd.accepted": "Қабылданды",
    "rd.workCompletion": "Жұмысты аяқтау",
    "rd.completionHint": "Өтінім жабылуы үшін клиент пен шебер жұмысты аяқтағанын растауы керек.",
    "rd.customer": "Клиент",
    "rd.worker": "Шебер",
    "rd.confirmed": "Расталды",
    "rd.pending": "Күтуде",
    "rd.markComplete": "Растау",
    "rd.budget": "Бюджет",
    "rd.negotiable": "Келісімді",
    "rd.initialPrice": "Бастапқы баға",
    "rd.postedBy": "Авторы",
    "rd.you": "Сіз",
    "rd.contactAfter": "Тағайындаудан кейін байланыс",
    "rd.makeOffer": "Ұсыныс жасау",
    "rd.offerSubmitted": "Ұсыныс жіберілді",
    "rd.youConfirmed": "Сіз аяқталғанын растадыңыз",
    "rd.markWorkComplete": "Жұмысты аяқтау",
    "rd.loginOffer": "Ұсыныс жасау үшін кіріңіз",

    "sc.greeting": "👋 Сәлем! Мен FixFlow көмекшісімін. Платформа жұмысы, өтінімдер, ұсыныстар, рейтингтер туралы кез келген сұрақ қойыңыз.",
    "sc.title": "FixFlow көмекшісі",
    "sc.subtitle": "Кез келген сұрақ қойыңыз",
    "sc.suggested": "Ұсыныстар:",
    "sc.placeholder": "Сұрағыңызды теріңіз...",
    "sc.s1": "Қалай өтінім жасаймын?",
    "sc.s2": "Ұсыныстар қалай жұмыс істейді?",
    "sc.s3": "Жұмысты қалай аяқталған деп белгілеу керек?",
    "sc.s4": "Рейтинг жүйесі қалай жұмыс істейді?",

    "auth.welcomeBack": "Қош келдіңіз",
    "auth.signInSubtitle": "FixFlow аккаунтыңызға кіріңіз",
    "auth.email": "Email",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Құпиясөз",
    "auth.signIn": "Кіру",
    "auth.noAccount": "Аккаунтыңыз жоқ па?",
    "auth.fillFields": "Барлық өрістерді толтырыңыз",
    "auth.welcomeBackToast": "Қош келдіңіз!",

    "reg.title": "Аккаунт құру",
    "reg.subtitle": "FixFlow-ке қосылыңыз",
    "reg.fullName": "Толық аты-жөні *",
    "reg.fullNamePlaceholder": "Ержан Ержанов",
    "reg.emailReq": "Email *",
    "reg.phone": "Телефон нөмірі",
    "reg.phonePlaceholder": "+7 (___) ___-__-__",
    "reg.passwordReq": "Құпиясөз *",
    "reg.create": "Аккаунт құру",
    "reg.haveAccount": "Аккаунтыңыз бар ма?",
    "reg.fillRequired": "Барлық міндетті өрістерді толтырыңыз",
    "reg.companyNameRequired": "Компания атауын енгізіңіз",
    "reg.createdToast": "Аккаунт сәтті құрылды!",
    "reg.alreadyExisted": "Аккаунт бұрыннан бар, сіз кірдіңіз.",
    "reg.roleCustomer": "Маған жөндеу қажет",
    "reg.roleWorker": "Мен қызмет көрсетемін",
    "reg.roleCompany": "Біз қызмет көрсетеміз",
    "reg.companyDetails": "Компания мәліметтері",
    "reg.companyName": "Компания атауы *",
    "reg.companyNamePlaceholder": "Acme Corp",
    "reg.companyDesc": "Сипаттама",
    "reg.companyDescPlaceholder": "Компанияңыз немен айналысады?",
    "reg.companyAddress": "Мекенжай",
    "reg.companyAddressPlaceholder": "Басты көшесі, 123",
    "reg.taxId": "БСН / ЖСН",
    "reg.website": "Веб-сайт",

    "prof.user": "Пайдаланушы",
    "prof.yourRating": "Сіздің рейтингіңіз",
    "prof.basedOnReviews": "Клиенттердің пікірлеріне негізделген",
    "prof.review": "пікір",
    "prof.reviews": "пікір",
    "prof.noReviews": "Пікірлер әлі жоқ. Рейтинг алу үшін жұмыстарды орындаңыз.",
    "prof.personalInfo": "Жеке ақпарат",
    "prof.personalInfoDesc": "Жеке мәліметтеріңізді жаңартыңыз",
    "prof.email": "Email",
    "prof.displayName": "Көрсетілетін аты",
    "prof.displayNamePlaceholder": "Сіздің атыңыз",
    "prof.phone": "Телефон",
    "prof.faceVerification": "Бет растамасы",
    "prof.faceVerificationDesc": "Бетіңізді тез сканерлеу арқылы тұлғаңызды растаңыз. Клиенттердің сенімін арттырады.",
    "prof.faceVerified": "Бет расталды",
    "prof.scanFace": "Бетті сканерлеу",
    "prof.rescan": "Қайта сканерлеу",
    "prof.certificate": "Біліктілік сертификаты",
    "prof.certificateDesc": "Біліктілігіңізді растайтын PDF жүктеңіз. Ұсыныстарыңызды қарайтын клиенттерге көрінеді.",
    "prof.certUploaded": "Сертификат жүктелді",
    "prof.view": "Ашу",
    "prof.noCert": "Сертификат әлі жүктелмеген.",
    "prof.replaceCert": "Сертификатты ауыстыру",
    "prof.uploadCert": "PDF сертификатын жүктеу",
    "prof.pdfHint": "Тек PDF, 10МБ дейін.",
    "prof.companyInfo": "Компания туралы ақпарат",
    "prof.companyInfoDesc": "Компанияңыздың деректерін басқарыңыз",
    "prof.companyName": "Компания атауы",
    "prof.description": "Сипаттама",
    "prof.descriptionPlaceholder": "Компанияңызды сипаттаңыз...",
    "prof.address": "Мекенжай",
    "prof.taxId": "БСН / ЖСН",
    "prof.website": "Веб-сайт",
    "prof.save": "Өзгерістерді сақтау",
    "prof.invalidFile": "Жарамсыз файл",
    "prof.invalidFileDesc": "Тек PDF файлдарына рұқсат етіледі.",
    "prof.fileTooLarge": "Файл тым үлкен",
    "prof.fileTooLargeDesc": "Максималды өлшем 10МБ.",
    "prof.certUploadedToast": "Сертификат жүктелді",
    "prof.certUploadedDesc": "Сіздің сертификатыңыз енді көрінеді.",
    "prof.uploadFailed": "Жүктеу сәтсіз",
    "prof.certRemoved": "Сертификат жойылды",
    "prof.error": "Қате",
    "prof.profileUpdated": "Профиль жаңартылды",
    "prof.profileUpdatedDesc": "Өзгерістеріңіз сақталды.",

    "new.back": "Өтінімдерге оралу",
    "new.title": "Жаңа өтінім жасау",
    "new.subtitle": "Қажетті жұмысты сипаттаңыз және мамандардан ұсыныстар алыңыз",
    "new.titleLabel": "Тақырып *",
    "new.titlePlaceholder": "Мысалы: ас үй кранын жөндеу",
    "new.category": "Санат *",
    "new.selectCategory": "Санатты таңдаңыз",
    "new.description": "Сипаттама *",
    "new.descriptionPlaceholder": "Мәселені толық сипаттаңыз...",
    "new.photos": "Фото (5-ке дейін)",
    "new.maxPhotos": "Максимум 5 фото",
    "new.city": "Қала",
    "new.cityPlaceholder": "Мысалы: Алматы",
    "new.district": "Аудан",
    "new.districtPlaceholder": "Мысалы: Бостандық",
    "new.address": "Мекенжай",
    "new.addressPlaceholder": "Көше, үй, пәтер",
    "new.budget": "Бюджет (₸)",
    "new.budgetPlaceholder": "Күтілетін бағаңыз",
    "new.aiSuggest": "ИИ ұсынысы",
    "new.aiEstimate": "ИИ бағасы (₸)",
    "new.useAmount": "Қолдану",
    "new.timeRange": "Қалаулы уақыт",
    "new.timeRangeHint": "Жұмыс қашан орындалу керек?",
    "new.startDate": "Басталу",
    "new.endDate": "Аяқталу",
    "new.posting": "Жариялануда...",
    "new.post": "Жариялау",
    "new.fillRequired": "Тақырыпты, сипаттаманы және санатты толтырыңыз",
    "new.posted": "Өтінім жарияланды!",
    "new.aiError": "ИИ қатесі",
    "new.titleCatFirst": "Алдымен тақырып пен санатты енгізіңіз",
    "new.error": "Қате",

    "my.title": "Менің өтінімдерім",
    "my.active": "Белсенді",
    "my.archive": "Мұрағат",
    "my.noActiveJobs": "Белсенді жұмыстар әлі жоқ",
    "my.noActive": "Белсенді өтінімдер жоқ",
    "my.browseRequests": "Өтінімдерді қарау",
    "my.postRequest": "Өтінім жасау",
    "my.noArchived": "Мұрағатталған өтінімдер жоқ",
    "my.archivedHint": "Аяқталған және тоқтатылған өтінімдер осында пайда болады",
    "my.myJob": "Менің жұмысым",

    "adm.accessOnly": "Тек әкімшілерге рұқсат",
    "adm.title": "Әкімші панелі",
    "adm.subtitle": "Өтінімдер мен пайдаланушыларды басқару",
    "adm.requests": "Өтінімдер",
    "adm.users": "Пайдаланушылар",
    "adm.noCity": "Қала жоқ",
    "adm.budget": "Бюджет",
    "adm.noPhone": "Телефон жоқ",
    "adm.noName": "(аты жоқ)",
    "adm.noRequests": "Өтінімдер жоқ",
    "adm.noUsers": "Пайдаланушылар жоқ",
    "adm.editRequest": "Өтінімді өңдеу",
    "adm.editUser": "Пайдаланушыны өңдеу",
    "adm.fTitle": "Тақырып",
    "adm.fDescription": "Сипаттама",
    "adm.fCategory": "Санат",
    "adm.fStatus": "Күй",
    "adm.fBudget": "Бюджет",
    "adm.fCity": "Қала",
    "adm.fDisplayName": "Көрсетілетін аты",
    "adm.fPhone": "Телефон",
    "adm.fRole": "Рөл",
    "adm.selectRole": "Рөлді таңдаңыз",
    "adm.cancel": "Бас тарту",
    "adm.save": "Сақтау",
    "adm.confirmDelete": "Бұл өтінімді біржола жою керек пе?",
    "adm.requestDeleted": "Өтінім жойылды",
    "adm.requestUpdated": "Өтінім жаңартылды",
    "adm.userUpdated": "Пайдаланушы жаңартылды",
  },
} as const;

type Key = keyof (typeof dict)["en"];

// Categories
const categoryDict: Record<string, { ru: string; kz: string }> = {
  Plumbing: { ru: "Сантехника", kz: "Сантехника" },
  Electrical: { ru: "Электрика", kz: "Электрика" },
  HVAC: { ru: "Кондиционеры", kz: "Желдеткіш" },
  Renovation: { ru: "Ремонт", kz: "Жөндеу" },
  Painting: { ru: "Покраска", kz: "Бояу" },
  Locksmith: { ru: "Замки", kz: "Құлыпшы" },
  "Appliance Repair": { ru: "Бытовая техника", kz: "Тұрмыстық техника" },
  Cleaning: { ru: "Уборка", kz: "Тазалау" },
  Other: { ru: "Другое", kz: "Басқа" },
};

const statusDict: Record<string, { en: string; ru: string; kz: string }> = {
  open: { en: "Open", ru: "Открыта", kz: "Ашық" },
  "in negotiation": { en: "In Negotiation", ru: "Обсуждается", kz: "Талқылануда" },
  assigned: { en: "Assigned", ru: "Назначена", kz: "Тағайындалды" },
  "in progress": { en: "In Progress", ru: "В работе", kz: "Жүруде" },
  in_progress: { en: "In Progress", ru: "В работе", kz: "Жүруде" },
  completed: { en: "Completed", ru: "Завершена", kz: "Аяқталды" },
  cancelled: { en: "Cancelled", ru: "Отменена", kz: "Тоқтатылды" },
  pending: { en: "Pending", ru: "Ожидает", kz: "Күтуде" },
  accepted: { en: "Accepted", ru: "Принято", kz: "Қабылданды" },
};

interface Ctx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: Key) => string;
  tCategory: (name: string) => string;
  tStatus: (name: string) => string;
}

const LanguageContext = createContext<Ctx | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const stored = (typeof window !== "undefined" && localStorage.getItem(STORAGE_KEY)) as Lang | null;
    if (stored && (stored === "en" || stored === "ru" || stored === "kz")) {
      setLangState(stored);
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem(STORAGE_KEY, l); } catch {}
  };

  const t = (k: Key) => (dict[lang] as Record<string, string>)[k] ?? (dict.en as Record<string, string>)[k] ?? k;

  const tCategory = (name: string) => {
    if (lang === "en") return name;
    return categoryDict[name]?.[lang] ?? name;
  };

  const tStatus = (name: string) => {
    const key = name.toLowerCase();
    return statusDict[key]?.[lang] ?? name;
  };

  return <LanguageContext.Provider value={{ lang, setLang, t, tCategory, tStatus }}>{children}</LanguageContext.Provider>;
};

export const useTranslation = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useTranslation must be used within LanguageProvider");
  return ctx;
};

